[project]
name = "po-chatbot"
version = "0.1.4"
description = "RAG-based chatbot for exam regulations at TH Köln"
authors = [
    { name = "Nikita B." }
]
dependencies = [
    "gradio",
    "chromadb",
    "sentence-transformers",
    "rank_bm25",
    "langchain-text-splitters",
    "pyyaml",
    "requests",
    "python-dotenv",
    "tqdm",
    "numpy",
    "pyngrok",
]
readme = "README.md"
requires-python = ">=3.11"

[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
target-version = "py311"
